-- Mini Dynamo gateway metadata schema.
-- Flyway owns the DDL; JPA runs in ddl-auto=validate against it, so entity
-- mappings and this file must stay in lockstep.

-- Node registry: which physical nodes the gateway knows about, synced from the
-- cluster's live ring (RING command). Distinct from the cluster's own in-memory
-- ring — this is the durable, queryable record for /v1/cluster/nodes.
CREATE TABLE nodes (
    id        VARCHAR(255) PRIMARY KEY,
    host      VARCHAR(255) NOT NULL,
    port      INTEGER      NOT NULL,
    added_at  TIMESTAMP    NOT NULL,
    last_seen TIMESTAMP
);

-- Versioned cluster configuration (the default N/W/R quorum knobs). Kept as an
-- append-only history rather than a single mutable row so a config change is an
-- auditable event, not an overwrite.
CREATE TABLE config_versions (
    version    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n          INTEGER   NOT NULL,
    w          INTEGER   NOT NULL,
    r          INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Administrative audit trail: who did what, when, and the before/after. Written
-- for mutating operations (e.g. DELETE) so administrative actions are traceable.
CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor      VARCHAR(255) NOT NULL,
    action     VARCHAR(64)  NOT NULL,
    target_key VARCHAR(512),
    before     TEXT,
    after      TEXT,
    at         TIMESTAMP    NOT NULL
);

-- Seed the default quorum configuration (Dynamo's classic N=3, W=2, R=2).
INSERT INTO config_versions (n, w, r, created_at) VALUES (3, 2, 2, now());
